---
# defaults file for kafka
kafka_version: 2.10-0.10.2.0
kafka_port: 9092
kafka_num_network_threads: 2
kafka_num_io_threads: 2
kafka_socket_send_buffer_bytes: 1048576
kafka_socket_receive_buffer_bytes: 1048576
kafka_socket_request_max_bytes: 104857600
kafka_log_dir: /var/log/kafka
kafka_num_partitions: 6
kafka_log_flush_interval_messages: 10000
kafka_log_flush_interval_ms: 1000
kafka_log_retention_bytes: 104857600
kafka_log_retention_hours: 1
kafka_log_segment_bytes: "{{kafka_log_retention_bytes}}"
zookeeper_cluster_hosts: 'elk_zookeeper'
kafka_cluster_hosts: 'elk_kafka'
zookeeper_connection_timeout_ms: 1000000
kafka_heap_opts: "-Xmx2G -Xms2G"
