#!/bin/sh

KAFKA_PATH=/opt/kafka
export JAVA_HOME=/usr/java/default

start() {
    if [ -f $KAFKA_PATH/bin/kafka-server-start.sh ]; then
        echo -n "Starting Kafka"
        $KAFKA_PATH/bin/kafka-server-start.sh -daemon $KAFKA_PATH/config/server.properties
        exit 0
    fi
}

stop() {
    if [ -f $KAFKA_PATH/bin/kafka-server-stop.sh ]; then
        echo -n "Stopping Kafka"
        $KAFKA_PATH/bin/kafka-server-stop.sh
        exit 0
    fi
}

case "$1" in
    'start')
        start
        ;;
    'stop')
        stop
        ;;
    'restart')
        stop
        start
        ;;
    *)
        echo "Usage: $0 { start | stop | restart }"
        ;;
esac
exit 0
