- name: disable selinux if it is enabled
  selinux: state=disabled
  tags: 
  - selinux
  - common

- name: copy elk repo to remote servers
  copy: src=elk.repo dest=/etc/yum.repos.d/
  tags: repo
  tags: 
  - repo
  - common

- name: set soft max open files
  lineinfile: dest=/etc/security/limits.conf line='* soft nofile 65535'
  tags: limits

- name: set hard max open files
  lineinfile: dest=/etc/security/limits.conf line='* hard nofile 65535'
  tags: limits
